# Generated by Django 2.0.6 on 2019-10-11 08:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrushSupplyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('BrushSize', models.CharField(max_length=4)),
                ('BrushType', models.CharField(max_length=10)),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CanvasSupplyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Size', models.CharField(max_length=10)),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplyCategory', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PaintSupplyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Color', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('SupplyType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyApp.Category')),
            ],
        ),
        migrations.AddField(
            model_name='canvassupplymodel',
            name='SupplyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyApp.Category'),
        ),
        migrations.AddField(
            model_name='brushsupplymodel',
            name='SupplyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyApp.Category'),
        ),
    ]
